server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
   gateway:
      routes:
        # Route pour l'Authentification et l'Admin
        - id: auth-route
          uri: lb://MS-AUTH-USER
          predicates:
            - Path=/api/auth/**, /api/admin/**

        # Route pour les Projets
        - id: projects-route
          uri: lb://MS-PROJECTS
          predicates:
            - Path=/api/projects/**
           

        # 3. Route pour le Backlog (Port 8083) - NOUVEAU
        - id: backlog-route
          uri: lb://MS-BACKLOG
          predicates:
            - Path=/api/backlog/**
      
      # Configuration Global CORS
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

# Configuration du client Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Configuration des Logs (pour le debug)
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG