apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-server-config
data:
  application.properties: |
    spring.application.name=discovery-server
    server.port=8761
    eureka.client.register-with-eureka=false
    eureka.client.fetch-registry=false
    eureka.instance.hostname=discovery-server
