apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-auth-user-config
data:
  application.properties: |
    server.port=8081
    spring.application.name=ms-auth-user

    spring.datasource.url=jdbc:mysql://mysql:3306/auth_db?createDatabaseIfNotExist=true
    spring.datasource.username=root
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true

    jwt.expiration-ms=86400000

    eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
