apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-backlog-config
data:
  application.properties: |
    server.port=8083
    spring.application.name=ms-backlog

    spring.datasource.url=jdbc:mysql://mysql:3306/backlog?createDatabaseIfNotExist=true
    spring.datasource.username=root
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true

    eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-notifications-config
data:
  application.properties: |
    server.port=8085
    spring.application.name=ms-notifications

    spring.datasource.url=jdbc:mysql://mysql:3306/notifications?createDatabaseIfNotExist=true
    spring.datasource.username=root
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true

    eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-sprints-config
data:
  application.properties: |
    server.port=8084
    spring.application.name=ms-sprints

    spring.datasource.url=jdbc:mysql://mysql:3306/sprints?createDatabaseIfNotExist=true
    spring.datasource.username=root
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true

    eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
